version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    networks:
      - app

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    depends_on:
      - api
    networks:
      - app

networks:
  app:
