version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "${API_PORT:-3000}:3000"
    networks:
      - app

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    ports:
      - "${UI_PORT:-80}:80"
    depends_on:
      - api
    networks:
      - app

networks:
  app:
